# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-6Q83T0T0JX"

# UI configs
title: "Creations by Audrey"
subtitle: "Images of my developed recipes"
author: "Audrey Sweetwood"
header:
 title: "Creations"
 subtitle: "by Audrey Sweetwood"
footer:
 name: "Audrey Sweetwood"
 bio: "I am a product development chef currently based in Baltimore, MD. I take pride in recipe development and nutrition education promoting general health and wellness. I have a Bachelor's Degree in Culinary Nutrition and a Master's Degree in Culinary Education, both from Johnson & Wales University in Providence, Rhode Island. I have worked for private clients, professional chefs, and Freshly Inc."
 github: "Please feel free to reach out to me with the Contact Form, or the social links below!"
web_design: "Jack Taubl"
social_urls:
  instagram: "https://www.instagram.com/audreysweetwood/?hl=en"
  linkedin: "https://www.linkedin.com/in/audrey-sweetwood"
